name: Trigger Child Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-child-1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child 1 Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/child_repository_1
          event-type: trigger-workflow
          token: ${{ secrets.GH_TOKEN }}
